version: "3"
services:
  selenoid:
    container_name: selenoid
    network_mode: bridge
    image: "aerokube/selenoid"
    command: -limit 4 -retry-count 1000
    ports:
      - 4444:4444
    volumes:
      - ./config:/etc/selenoid:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/c/selenoid/video/aerokube
  selenoid-ui:
      image: "aerokube/selenoid-ui"
      network_mode: bridge
      links:
        - selenoid
      ports:
        - "8080:8080"
      command: ["--selenoid-uri", "http://selenoid:4444"]